### ISSUE TITLE
Add Person Success Title Wrong

### ISSUE THREAD

**Issue by MIDNJLH** [JarrahGos/TOC19#20]
Once the program has completed adding a person, it comes up with a window which, instead of being titled "success" is titled "Person has been added to the system" and the message is success. they have been swapped.

**Comment by JarrahGos** [comment]
Solved. Title and message now reversed. 
https://github.com/jarrah-95/TOC19/commit/5fa91f49b7a7ec79389b7355e9861fd31ed3c1e5
