### ISSUE TITLE
Admin Menu order is not logical

### ISSUE THREAD

**Issue by MIDNJLH** [JarrahGos/TOC19#26]
Order the menu items in the Admin menu in order of use.
Or follow picture from before.
![img_20140501_132029](https://cloud.githubusercontent.com/assets/7455369/2850150/88081ce4-d0f4-11e3-86d7-fd65959fe584.jpg)

**Comment by JarrahGos** [comment]
Resolved in fec51cba518a6acba4ff3d7e47bbd1f106f53311 with the new admin menu.
