### ISSUE TITLE
Phantom User

### ISSUE THREAD

**Issue by Tinkerlad0** [JarrahGos/TOC19#52]
Attempting to enter a PMKeyS of "7000000" creates a phantom user of username "5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8" that appears under 'List People' and 'Remove People' on the admin interface. 

however attempting to log in as you would with PMKeYs to purchase items results in the program not finding the user. I had a look at the code and saw that you blacklist this entry into the input however I don't believe the phantom user is intentional.

http://puu.sh/gWkrZ/756f20cdb1.png

**Comment by JarrahGos** [comment]
This is due to the legacy method of getting into the admin user. You can no longer create a user with the PMKeyS of 7000000 as of aa218f8327324b0e79d209527d61c2a48bbf52ba
