### ISSUE TITLE
Handling of Invalid characters

### ISSUE THREAD

**Issue by Tinkerlad0** [JarrahGos/TOC19#56]
At the moment an invalid character is handled by simply printing the stacktrace to the console and nothing else. This offers no feedback to the user about the issue and leaves all the text as it stands. Perhaps we could look at highlighting the invalid characters or some other feedback on the TextFields.

**Comment by JarrahGos** [comment]
Not quite sure what you are talking about in this one. On mine, when I enter the wrong barcode (either for person or product) the whole textfield flashes red and the text is cleared. 

What happens on yours?

**Comment by Tinkerlad0** [comment]
Sorry should have added more clarification, To test look at adding a Product in the admin screen. When you have a price of "52.2.25" ie. an illegal value, the enter key appears to do nothing and the console prints a stacktrace of [this](http://www.hastebin.com/tarukixiru.avrasm). There is no feedback to the user at all apart from the lack of action.
